CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120)   NOT NULL,
    email      VARCHAR(180)   NOT NULL UNIQUE,
    cohort     VARCHAR(20)    NOT NULL,
    created_at TIMESTAMP      NOT NULL
);

CREATE TABLE plans (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_cycle VARCHAR(20)    NOT NULL UNIQUE,
    price         DECIMAL(12, 2) NOT NULL
);

CREATE TABLE tiers (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(20) NOT NULL UNIQUE,
    level INT         NOT NULL
);

CREATE TABLE benefits (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_id       BIGINT       NOT NULL REFERENCES tiers (id),
    type          VARCHAR(30)  NOT NULL,
    benefit_value VARCHAR(120) NOT NULL
);

CREATE TABLE tier_criteria (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_id           BIGINT         NOT NULL UNIQUE REFERENCES tiers (id),
    min_order_count   INT            NOT NULL,
    min_monthly_spend DECIMAL(12, 2) NOT NULL,
    required_cohort   VARCHAR(20)
);

CREATE TABLE membership_activity (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL UNIQUE REFERENCES users (id),
    order_count  INT            NOT NULL,
    monthly_spend DECIMAL(12, 2) NOT NULL,
    total_spend  DECIMAL(12, 2) NOT NULL,
    window_start DATE           NOT NULL
);

CREATE TABLE subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    plan_id    BIGINT      NOT NULL REFERENCES plans (id),
    tier_id    BIGINT      NOT NULL REFERENCES tiers (id),
    status     VARCHAR(20) NOT NULL,
    start_date DATE        NOT NULL,
    end_date   DATE        NOT NULL,
    version    BIGINT      NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL
);

CREATE INDEX ix_subscriptions_user_status ON subscriptions (user_id, status);

-- Note: "at most one ACTIVE subscription per user" is enforced in the service layer.
-- On PostgreSQL it can additionally be guaranteed with a partial unique index:
--   CREATE UNIQUE INDEX ux_active_subscription_per_user
--       ON subscriptions (user_id) WHERE status = 'ACTIVE';
-- H2 does not support partial indexes, so it is omitted here for a portable schema.